<?php
$intro1 = "STAL LIMITED is a company based in Kenya which deals in construction  services. We provide Construction Management and General Contracting to retail industrial, medical and civil markets. Our goals are to build lasting relationships with Owners and with our trade contractors by conducting business in a sound and ethical manner, and to provide superior performance, expedient solutions, and an excellent value. We provide solutions to your most challenging construction projects, small or large.";

$mission = "STAL LIMITED is committed to building long-term relationships based on integrity, performance, value, and client satisfaction. <br /><br />We will continue to meet the changing needs of our clients with our quality services delivered by the most qualified people.";

$vision = "STAL LIMITED is not just a construction company. We are a dedicated team striving to bring growth to our community, helping to maintain existing companies and assist our clients in making their dreams become a reality <br /><br /> Our company is based on the belief that our customers' needs are of the utmost importance. Our entire team is committed to meeting those needs. As a result, a high percentage of our business is from repeat customers and referrals. <br /><br />Whether you have a need for a private residential building or civil works, we would welcome the opportunity to earn your trust and deliver you the best service in the industry.";

$howwork = "STAL LIMITED  submits bid proposals in a timely manner and offers competitive pricing. We provide shop drawings, design calculations and field dimensions (as necessary). We also provide front-end documents, such as Hazard Communications Program, MSDS Booklet of Materials Used, Alcohol and Drug Policy, Safety Program, Maintenance Procedures, and company personnel contacts are sent at the outset.<br /><br />Once a project has been awarded, we issue an itemized schedule of work using the latest scheduling techniques, which is used for managing progress throughout the entire project. Our Project Management, Engineering and Production staffs begin a dialogue with the customer's field and office staff to coordinate the work. Fabrication and field installation are scheduled and coordinated through the appropriate parties to ensure all work is fabricated correctly and installed in a sequence as to not delay other trades.<br /><br />When you hire our construction management team, you get all the perks of our years of experience  focused on your specific project. Clients often turn to STAL LIMITED for construction management. We put our experienced management teams to work for you, controlling costs, schedules, quality, and safety.<br /><br />Our teams consist of Project Managers, General Superintendents, Field Superintendents, Project Manager Assistants and Vice Presidents of Project Management to ensure that our evaluation of your project’s every facet leads to a cost-effective, quality, safe project and on-time delivery. From planning to coordinating the project, we help with all aspects of the build.<br /><br />STAL LIMITED at-Risk services, that shift all the contractual risks and responsibilities to our team as well, further mitigating the stress of a very complex experience.";

$constructionservices = "Our Construction Services Include<br /><br /><ul><li>Residential Housing</li><li>Commercial Building</li><li>Civil Works</li><li>Borehole Drilling</li></ul>";

$employeepolicy = "Our policy is implemented by all employees. Our commitment involves:<br /><br /><ul><li>Reducing waste levels and actively recycling waste materials for re use</li><li>Carefully monitoring scrap materials in accordance with quality procedures</li><li>Making sure energy use is monitored through a programme of improvement to ensure maximum efficiency</li><li>Considering the locality in which the materials are sourced in relation to their end use location.</li><li>Monitoring fuel use.</li><li>Training employees and raising awareness with procedures and responsibilities</li><li>Ensuring activities are carried out with minimal impact on local communities and not creating a nuisance to our neighbours</li><li>Carefully vetting our suppliers to ensure their commitment and standards are equal to ours</li><li>Continually strive to improve and review objective and targets annually</li><li>Ensure our policy meets the current  legislation and industry best practices</li></ul>";

$environpolicy = "STAL LIMITED is committed to providing unparalleled standards and quality of service to all of its customers. We believe that this can and must be done in a way, which protects and enhances the environment. It is a fundamental part of our business policy that we should aim to avoid losses and maximise benefits. It follows that we must minimise adverse environmental effects arising from our business activities and promote a positive attitude to the conservation and enhancement of all aspects of our environment. Environmental factors will be taken into consideration in our business planning and decision making.<br /><br />We’ve always taken jobsite safety very seriously. Stressing that safety is everyone’s responsibility, we have consistently achieved high ratings. Rest assured we’ll take every precaution possible to keep everyone safe throughout the duration your construction project.";

$safetypre = "<ul><li>Our Dedicated Safety Director routinely conducts jobsite audits, working in-tandem with your Project Manager and Site Supervisor to ensure safety is triple-checked from the top down.</li><li>Scheduled “toolbox talks” where your Site Supervisor will discuss any safety issues or concerns with the entire team. These meetings are documented and everyone in attendance is required to acknowledge the training.</li><li>Everyone strives to maintain compliance during the entire project - to keep each individual safe and your job moving without delay.</li>
</ul>";




?>